#! /usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Usage: python image_to_b64 /path/to/your_image
"""

import sys
import os


def get_file_data_uri(file_path):
    '''Convert file to data URI'''
    if not file_path:
        return None

    from base64 import b64encode
    from mimetypes import guess_type
    with open(file_path, 'rb') as f:
        content = f.read()
    mime_type = guess_type(file_path)[0]
    file_name = os.path.split(file_path)[-1]

    return (
        '<img src="data:%(mime_type)s;base64,%(b64)s" '
        'alt="%(filename)s"></img>'
        % {
            "mime_type": mime_type,
            "b64": b64encode(content).decode(),
            "filename": file_name
    })


if __name__ == "__main__":
    if len(sys.argv) > 1:
        file_path = sys.argv[1]
        with open("%sb64.txt" % file_path, 'w') as f:
            f.write(get_file_data_uri(file_path))
    else:
        raise RuntimeError("image path not specified")


